spring:
  datasource:  # Database configuration
    driver-class-name: com.mysql.jdbc.Driver
    username: song0240 # root
    password: 123456 # 123456
    url: jdbc:mysql://106.53.192.192:3306/user_center # jdbc:mysql://localhost:3306/syy
  session:
    timeout: 86400   # Session fail time

#server:
#  address: 106.53.192.192